server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url:    jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: root
    password: Mamaitata1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000